<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "network".
 *
 * @property int $id
 * @property int $tmd_id
 * @property string|null $name
 *
 * @property TvNetwork[] $tvNetworks
 * @property Tv[] $tvs
 */
class Network extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'network';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tmd_id'], 'required'],
            [['tmd_id'], 'integer'],
            [['name'], 'string', 'max' => 100],
            [['tmd_id'], 'unique'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'tmd_id' => 'Tmd ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTvNetworks()
    {
        return $this->hasMany(TvNetwork::className(), ['network_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTvs()
    {
        return $this->hasMany(Tv::className(), ['id' => 'tv_id'])->viaTable('tv_network', ['network_id' => 'id']);
    }

    public function beforeDelete()
    {
        $poster = Yii::getAlias('@webroot') . '/i/n/' . $this->id . '.png';
        if (file_exists($poster)) {
            unlink($poster);
        }

        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
